src/GitWeek07/www/dtest/recipes/urls.py
'''
Created on Feb 23, 2011

@author: mlr
'''

from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('recipes.views',
    (r'^$', 'index'),
    (r'^(?P<recipe_id>\d+)/$', 'detail'),
    (r'ingredient/(?P<ingredient_name>\w+)/$', 'ingredient'),
    (r'tags/$', 'tags'),
    (r'tags/(?P<tag_name>\w+)/$', 'tagged'),
)

src/GitWeek07/www/dtest/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Recipes
    (r'^recipes/',include('recipes.urls')),

    # Json Polls API
    #(r'^jrecipes/', include('jrecipes.urls')),

    # Admin docs
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Admin:
    (r'^admin/', include(admin.site.urls)),

    # Site Media
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    
    # Default:
    (r'^$', 'views.index')
)

handler404 = 'views.error404'

src/GitWeek07/www/dtest/recipes/models.py
from django.db import models

class Tag(models.Model):
    name = models.CharField(max_length=25)
    def __unicode__(self):
            return self.name    
    

class Ingredient(models.Model):
    UNIT_CHOICES = (
        ('C', 'Cups'),
        ('c', 'Cup'),
        ('B', 'Tbs'),
        ('S', 'tsp'),
        ('L', 'lbs'),    
        ('l', 'lb'), 
        ('O', 'oz'),   
        ('N', ' '),    
    )
    order   = models.PositiveSmallIntegerField()
    amount  = models.FloatField()
    units   = models.CharField(max_length=1, choices=UNIT_CHOICES)
    name    = models.CharField(max_length=30)
    remark  = models.CharField(max_length=80,blank=True)
    recipe  = models.ForeignKey('Recipe')
    def safeName(self):
        return self.name.replace(" ","_")
    def __unicode__(self):
            return self.name    

class Instruction(models.Model):
    order    = models.PositiveSmallIntegerField()
    summary  = models.CharField(max_length=25)
    detail   = models.CharField(max_length=500)
    recipe   = models.ForeignKey('Recipe')
    def __unicode__(self):
            return self.summary

class Recipe(models.Model):
    title    = models.CharField(max_length=80)
    source   = models.CharField(max_length=80)
    servings = models.PositiveSmallIntegerField()
    tags     = models.ManyToManyField(Tag)
    #prep_time = models.??timedelta??
    #total_time = models.??timedelta??
    def __unicode__(self):
            return self.title    



'''
Wed:   Basic recipe working with:
  
  Views:
           
          - title, source, number of servings, ingredients, instructions
         Ingredients table working with:
           - number, name, amount (initially as float), units (enum)
         Instructions working with:
           - number, summary, detail
         Unit tests
         See a list of all recipes
         Click on a recipe in list to see recipe detail


class Tag?s?(models.Model):
    name = models.CharField(max_length=80)
    ?? how to link to other objects (many-to-many example)

class MenuItem(models.Model):
    order = ??int??
    recipe title or text field??
    
class Menu?s?(models.Model):
    ?? ordered list of recipes ??
    
        

'''


src/GitWeek07/www/dtest/recipes/views.py
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from recipes.models import Instruction, Ingredient, Recipe, Tag
from django.shortcuts import render_to_response, get_object_or_404
from django.conf import settings


def index(request):
    recipeList = Recipe.objects.all().order_by('title')[:]
    tagList = Tag.objects.all().order_by('name')[:]
    return render_to_response('recipes/index2.html', {'recipeList':recipeList,'tagList':tagList})

def detail(request, recipe_id):
    r = get_object_or_404(Recipe, pk=recipe_id)
    return render_to_response('recipes/detail3.html', {'recipe':r,'MEDIA_ROOT':settings.MEDIA_ROOT}, 
                               context_instance=RequestContext(request))

def ingredient(request, ingredient_name):
    ingredient_name = ingredient_name.replace("_"," ")
    recipes = Recipe.objects.filter(ingredient__name__contains=ingredient_name)
    return render_to_response('recipes/ingredient2.html', {'recipes':recipes,'ingredientName':ingredient_name}, context_instance=RequestContext(request))

def tagged(request, tag_name):
    recipes = Recipe.objects.filter(tags__name__contains=tag_name)
    return render_to_response('recipes/tagged2.html', {'recipes':recipes,'tagName':tag_name}, context_instance=RequestContext(request))

def tags(request):
    tagList = Tag.objects.all().order_by('name')[:]
    return render_to_response('recipes/tags.html', {'tagList':tagList})



src/GitWeek07/www/dtest/views.py
'''
Created on Feb 23, 2011

@author: mlr
'''

from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from recipes.models import Instruction, Ingredient, Recipe
from django.shortcuts import render_to_response, get_object_or_404

def index(request):
    return render_to_response('index.html')


src/GitWeek07/www/dtest/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE|default:"en-us" }}" 
      xml:lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>Recipe Central</title>
<link rel="stylesheet" type="text/css" href="/static/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/css/dashboard.css" />
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/static/css/ie.css" /><![endif]-->
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock%}
</head>
<body class="dashboard">
<!-- Container -->
<div id="container">
  <!-- Header -->
  <div id="header">
    <!-- Branding -->
    <div id="branding">
      <h1 id="site-name">Recipe Central Demo Site</h1>
    </div>
    <!-- END Branding -->
    <!-- User-tools -->
    <div id="user-tools">
      Home &nbsp &nbsp | &nbsp &nbsp   <a href="/recipes/">Recipe List</a> &nbsp &nbsp | &nbsp &nbsp   <a href="/admin/recipes/">Add Recipe (staff only)</a>
    </div>
    <!-- END User-tools -->
  </div>
  <!-- END Header -->

  <!-- Content colMS-->
  <div id="content" class="colMS">


<h1>What's this?</h1>

<p>Welcome to the Recipe Central Demonstration Site. You can view recipes and click on ingredients or tags 
to find more recipes with those ingredients or tags. If you have a staff login you can add recipes. Not 
everything is working yet, so please be patient... thanks! </p>

<a href="/recipes/">See the recipes...</a>

  <br class="clear" />
  </div>
  <!-- END Content colMS-->
</div>
<!-- END Container -->

</body>
</html>


src/GitWeek07/www/dtest/templates/recipes/detail3.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE|default:"en-us" }}" xml:lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}> 
<head> 
<title>{{ recipe.title }}</title> 
<link rel="stylesheet" type="text/css" href="/static/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/css/dashboard.css" />
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/static/css/ie.css" /><![endif]-->
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>

<body class="dashboard"> 
<!-- Container --> 
<div id="container"> 
  <!-- Header --> 
  <div id="header"> 
    <!-- Branding --> 
    <div id="branding"> 
      <h1 id="site-name">Recipe Central</h1> 
    </div> 
    <!-- END Branding --> 
    <!-- User-tools -->      
    <div id="user-tools"> 
      <a href="/">Home</a> ... <a href="/recipes/">Recipe List</a> ... {{ recipe.title }}
    </div> 
    <!-- END User-tools -->      
  </div> 
  <!-- END Header --> 

  <!-- Content colMS--> 
  <div id="content" class="colMS"> 
        

<h1>{{ recipe.title }}</h1>

<!-- content-main--> 
<div id="content-main"> 

<p> Serves: &nbsp {{ recipe.servings }}</p>
<h4>Ingredients:</h4>
<table border="0">
{% for ingredient in recipe.ingredient_set.all|dictsort:"order" %}
   <tr><td> &nbsp &nbsp {{ ingredient.amount|floatformat }} &#x2009 {{ ingredient.get_units_display }} &nbsp </td><td> 
   <a href="../ingredient/{{ ingredient.safeName }}">{{ ingredient.name }}</a>{{ ingredient.remark }} </td></tr>
{% endfor %}
</table>
<h4>Instructions:</h4>
<ol>
{% for instruction in recipe.instruction_set.all|dictsort:"order" %}
    <li><b>{{ instruction.summary }}</b> <br/> <p> {{ instruction.detail }}</p></li>
{% endfor %}
</ol>
<p> Source: &nbsp {{ recipe.source }}</p>
</div> 
<!-- END content-main--> 
<!-- content-related--> 
<div id="content-related"> 
<!-- recent-actions-module--> 
<div class="module" id="recent-actions-module"> 

<h4>Tags:</h4><p>
{% for tag in recipe.tags.all %} 
    <a href="../tags/{{ tag.name }}">{{ tag.name }}</a> &nbsp
{% endfor %}
</p>

  </div>  
<!-- END recent-actions-module--> 
</div> 
<!-- END content-related--> 
 
  <br class="clear" /> 
  </div>
  <!-- END Content colMS--> 
 
  <div id="footer"></div> 
</div> 
<!-- END Container --> 
 
</body> 
</html> 

src/GitWeek07/www/dtest/templates/recipes/index2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE|default:"en-us" }}" xml:lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}> 
<head> 
<title>Recipes</title> 
<link rel="stylesheet" type="text/css" href="/static/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/css/dashboard.css" />
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/static/css/ie.css" /><![endif]-->
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>

<body class="dashboard"> 
<!-- Container --> 
<div id="container"> 
  <!-- Header --> 
  <div id="header"> 
    <!-- Branding --> 
    <div id="branding"> 
      <h1 id="site-name">Recipe Central</h1> 
    </div> 
    <!-- END Branding --> 
    <!-- User-tools -->      
    <div id="user-tools"> 
      <a href="/">Home</a> ... <a href="/recipes/tags/">Tag List</a> ... Recipes
    </div> 
    <!-- END User-tools -->      
  </div> 
  <!-- END Header --> 

  <!-- Content colMS--> 
  <div id="content" class="colMS"> 
        

<h1>Recipes</h1>

<!-- content-main--> 
<div id="content-main"> 

{% if recipeList %}
    <ul>
    {% for recipe in recipeList %}
        <li><a href="/recipes/{{ recipe.id }}/">{{ recipe.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No recipes are available.</p>
{% endif %}

</div> 
<!-- END content-main--> 
<!-- content-related--> 
<div id="content-related"> 
<!-- recent-actions-module--> 
<div class="module" id="recent-actions-module"> 

<h4>Tags:</h4><p>
{% for tag in tagList %} 
    <a href="/recipes/tags/{{ tag.name }}">{{ tag.name }}</a>  
{% endfor %}
</p>

  </div>  
<!-- END recent-actions-module--> 
</div> 
<!-- END content-related--> 
 
  <br class="clear" /> 
  </div>
  <!-- END Content colMS--> 
 
  <div id="footer"></div> 
</div> 
<!-- END Container --> 
 
</body> 
</html> 

src/GitWeek07/www/dtest/templates/recipes/ingredient.html
<h1>Recipes containing {{ ingredientName }}:</h1>
<ul>
{% for recipe in recipes %}
   <li><a href= "/recipes/{{ recipe.id }}/">{{ recipe.title }} </a> </li> 
{% endfor %}
</ul>

src/GitWeek07/www/dtest/templates/recipes/ingredient2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE|default:"en-us" }}" xml:lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}> 
<head> 
<title>Recipes</title> 
<link rel="stylesheet" type="text/css" href="/static/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/css/dashboard.css" />
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/static/css/ie.css" /><![endif]-->
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>

<body class="dashboard"> 
<!-- Container --> 
<div id="container"> 
  <!-- Header --> 
  <div id="header"> 
    <!-- Branding --> 
    <div id="branding"> 
      <h1 id="site-name">Recipe Central</h1> 
    </div> 
    <!-- END Branding --> 
    <!-- User-tools -->      
    <div id="user-tools"> 
      <a href="/">Home</a> ... <a href="/recipes/tags/">Tag List</a> ... <a href="/recipes/">RecipeList</a> ... {{ tagName }}  Recipes
    </div> 
    <!-- END User-tools -->      
  </div> 
  <!-- END Header --> 

  <!-- Content colMS--> 
  <div id="content" class="colMS"> 
        

<h1>Recipes containing {{ ingredientName }}:</h1>

<!-- content-main--> 
<div id="content-main"> 

<ul>
{% for recipe in recipes %}
   <li><a href= "/recipes/{{ recipe.id }}/">{{ recipe.title }} </a> </li>
{% endfor %}
</ul>

</div> 
<!-- END content-main-->  
  <br class="clear" /> 
  </div>
  <!-- END Content colMS--> 
 
  <div id="footer"></div> 
</div> 
<!-- END Container --> 
 
</body> 
</html> 

src/GitWeek07/www/dtest/templates/recipes/old/detail.html
<h1>{{ recipe.title }}</h1>
<p> Serves: &nbsp {{ recipe.servings }}</p>
<h4>Ingredients:</h4>
<table border="0">
{% for ingredient in recipe.ingredient_set.all|dictsort:"order" %}
   <tr><td> &nbsp &nbsp {{ ingredient.amount|floatformat }} &#x2009 {{ ingredient.get_units_display }} &nbsp </td><td> 
   <a href="../ingredient/{{ ingredient.name }}">{{ ingredient.name }}</a> </td></tr>
{% endfor %}
</table>
<h4>Instructions:</h4>
<ol>
{% for instruction in recipe.instruction_set.all|dictsort:"order" %}
    <li><b>{{ instruction.summary }}</b> <br/> <p> {{ instruction.detail }}</p></li>
{% endfor %}
</ol>
<h4>Tags:</h4><p>
{% for tag in recipe.tags.all %} 
    <a href="../tags/{{ tag.name }}">{{ tag.name }}</a> &nbsp
{% endfor %}
</p>
<p> Source: &nbsp {{ recipe.source }}</p>

src/GitWeek07/www/dtest/templates/recipes/old/detail2-complex.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE|default:"en-us" }}" xml:lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}> 
<head> 
<title>{{ recipe.title }}</title> 
<link rel="stylesheet" type="text/css" href="{% MEDIA_ROOT %}css/base.css" />
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% MEDIA_ROOT %}css/ie.css" /><![endif]-->
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body>


</body>
</html>

src/GitWeek07/www/dtest/templates/recipes/old/detail2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE|default:"en-us" }}" xml:lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}> 
<head> 
<title>{{ recipe.title }}</title> 
<link rel="stylesheet" type="text/css" href="{% MEDIA_ROOT %}css/base.css" />
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% MEDIA_ROOT %}css/ie.css" /><![endif]-->
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body>

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% if user.is_active and user.is_staff %}
        <div id="user-tools">
            {% trans 'Welcome,' %}
            <strong>{% filter force_escape %}{% firstof user.first_name user.username %}{% endfilter %}</strong>.
            {% block userlinks %}
                {% url django-admindocs-docroot as docsroot %}
                {% if docsroot %}
                    <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                {% endif %}
                {% url admin:password_change as password_change_url %}
                {% if password_change_url %}
                    <a href="{{ password_change_url }}">
                {% else %}
                    <a href="{{ root_path }}password_change/">
                {% endif %}
                {% trans 'Change password' %}</a> /
                {% url admin:logout as logout_url %}
                {% if logout_url %}
                    <a href="{{ logout_url }}">
                {% else %}
                    <a href="{{ root_path }}logout/">
                {% endif %}
                {% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}<div class="breadcrumbs"><a href="/">{% trans 'Home' %}</a>{% if title %} &rsaquo; {{ title }}{% endif %}</div>{% endblock %}
    {% endif %}

        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	{% endfor %}</ul>
        {% endif %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

src/GitWeek07/www/dtest/templates/recipes/old/index.html
{% if recipeList %}
    <ul>
    {% for recipe in recipeList %}
        <li><a href="/recipes/{{ recipe.id }}/">{{ recipe.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No recipes are available.</p>
{% endif %}

src/GitWeek07/www/dtest/templates/recipes/old/tagged.html
<h1>Recipes tagged as {{ tagName }}:</h1>
<ul>
{% for recipe in recipes %}
   <li><a href= "/recipes/{{ recipe.id }}/">{{ recipe.title }} </a> </li> 
{% endfor %}
</ul>

src/GitWeek07/www/dtest/templates/recipes/tagged2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE|default:"en-us" }}" xml:lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}> 
<head> 
<title>Recipes</title> 
<link rel="stylesheet" type="text/css" href="/static/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/css/dashboard.css" />
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/static/css/ie.css" /><![endif]-->
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>

<body class="dashboard"> 
<!-- Container --> 
<div id="container"> 
  <!-- Header --> 
  <div id="header"> 
    <!-- Branding --> 
    <div id="branding"> 
      <h1 id="site-name">Recipe Central</h1> 
    </div> 
    <!-- END Branding --> 
    <!-- User-tools -->      
    <div id="user-tools"> 
      <a href="/">Home</a> ... <a href="/recipes/tags/">Tag List</a> ... <a href="/recipes/">RecipeList</a> ... {{ tagName }}  Recipes
    </div> 
    <!-- END User-tools -->      
  </div> 
  <!-- END Header --> 

  <!-- Content colMS--> 
  <div id="content" class="colMS"> 
        

<h1>{{ tagName }} Recipes:</h1>

<!-- content-main--> 
<div id="content-main"> 

<ul>
{% for recipe in recipes %}
   <li><a href= "/recipes/{{ recipe.id }}/">{{ recipe.title }} </a> </li>
{% endfor %}
 
</div> 
<!-- END content-main-->  
  <br class="clear" /> 
  </div>
  <!-- END Content colMS--> 
 
  <div id="footer"></div> 
</div> 
<!-- END Container --> 
 
</body> 
</html> 

src/GitWeek07/www/dtest/templates/recipes/tags.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE|default:"en-us" }}" xml:lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}> 
<head> 
<title>Recipes</title> 
<link rel="stylesheet" type="text/css" href="/static/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/css/dashboard.css" />
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/static/css/ie.css" /><![endif]-->
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>

<body class="dashboard"> 
<!-- Container --> 
<div id="container"> 
  <!-- Header --> 
  <div id="header"> 
    <!-- Branding --> 
    <div id="branding"> 
      <h1 id="site-name">Recipe Central</h1> 
    </div> 
    <!-- END Branding --> 
    <!-- User-tools -->      
    <div id="user-tools"> 
      <a href="/">Home</a> ... <a href="/recipes/">Recipe List</a> ... Recipe Tags
    </div> 
    <!-- END User-tools -->      
  </div> 
  <!-- END Header --> 

  <!-- Content colMS--> 
  <div id="content" class="colMS"> 
        

<h1>Recipe Tags</h1>

<!-- content-main--> 
<div id="content-main"> 

{% if tagList %}
    <ul>
    {% for tag in tagList %}
        <li><a href="/recipes/tags/{{ tag.name }}/">{{ tag.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No recipe tags are available.</p>
{% endif %}

</div> 
<!-- END content-main--> 
 
  <br class="clear" /> 
  </div>
  <!-- END Content colMS--> 
 
  <div id="footer"></div> 
</div> 
<!-- END Container --> 
 
</body> 
</html> 